# Generated by Django 4.2.9 on 2024-12-06 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_Name', models.CharField(default='user', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentModel',
            fields=[
                ('shipment_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('shipment_category', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=20)),
                ('status', models.CharField(default='yet to be shipped', max_length=500)),
                ('transanctionNumber', models.IntegerField(unique=True)),
                ('date', models.DateField(default=datetime.date(2024, 12, 6))),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapi.rolemodel')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapi.rolemodel'),
        ),
    ]
