# Generated by Django 4.2.9 on 2024-12-08 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 12, 8)),
        ),
        migrations.AlterField(
            model_name='shipmentmodel',
            name='status',
            field=models.CharField(blank=True, default='yet to be shipped', max_length=500),
        ),
    ]
